// GENERATED by tools/art/measure_content_boxes.mjs — do not edit by hand.
// Re-run that script after changing any structure art.
//
// The box each structure's VISIBLE pixels occupy inside its frame, as the
// UNION across every frame of its atlas (a per-frame box would rescale the
// sprite as the animation advanced). Coordinates are frame-local pixels.
//
// The renderer fits this box — not the frame — to the footprint, so authored
// margin is not rendered as blank tile, and the box's bottom edge is the
// structure's ground line.
export const STRUCTURE_CONTENT_BOX = {
  hall: { x: 7, y: 2, w: 50, h: 60, frameW: 64, frameH: 64 },
  barricade: { x: 0, y: 1, w: 32, h: 29, frameW: 32, frameH: 32 },
  snare_post: { x: 4, y: 0, w: 55, h: 63, frameW: 64, frameH: 64 },
  watchtower: { x: 4, y: 0, w: 39, h: 60, frameW: 48, frameH: 64 },
  farm: { x: 5, y: 4, w: 22, h: 22, frameW: 32, frameH: 32 },
  marketplace: { x: 1, y: 8, w: 62, h: 48, frameW: 64, frameH: 64 },
  earth_special: { x: 2, y: 1, w: 60, h: 28, frameW: 64, frameH: 32 },
  fire_special: { x: 2, y: 5, w: 92, h: 52, frameW: 96, frameH: 64 },
  water_special: { x: 2, y: 0, w: 60, h: 57, frameW: 64, frameH: 64 },
  wind_special: { x: 2, y: 0, w: 60, h: 57, frameW: 64, frameH: 64 },
  magma_trap: { x: 2, y: 2, w: 124, h: 124, frameW: 128, frameH: 128 },
  firestorm: { x: 4, y: 10, w: 88, h: 76, frameW: 96, frameH: 96 },
  muddy_bog: { x: 2, y: 4, w: 60, h: 56, frameW: 64, frameH: 64 },
  blizzard: { x: 2, y: 5, w: 60, h: 54, frameW: 64, frameH: 64 },
  steam_vent: { x: 0, y: 9, w: 128, h: 112, frameW: 128, frameH: 128 },
  grinder: { x: 0, y: 4, w: 128, h: 119, frameW: 128, frameH: 128 },
}
