// Guards the art/manifest/<id>.json split (2026-08-13): the fragments are
// the editable source of truth, art/assets-manifest.json is generated by
// `npm run build:manifest` and committed so every existing reader keeps
// working unchanged. Parallel asset-packaging sessions only ever touch their
// own fragment file, never the generated ledger — see
// docs/handoffs/2026-08-13-codex-parallel-asset-dispatch.md. This test does
// NOT require every fragment to already be aggregated (a session's fragment
// can exist before its asset is merged/rebuilt into the ledger); it only
// catches drift once a fragment IS present in the aggregated ledger, or a
// fragment file whose name doesn't match its own id.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readdirSync, readFileSync } from 'node:fs'

const FRAGMENT_DIR = new URL('../../art/manifest/', import.meta.url)
const fragmentFiles = readdirSync(FRAGMENT_DIR).filter((f) => f.endsWith('.json') && f !== '_root.json')
const aggregated = JSON.parse(readFileSync(new URL('../../art/assets-manifest.json', import.meta.url), 'utf8'))
const aggregatedById = new Map(aggregated.assets.map((a) => [a.id, a]))

test('every art/manifest/<id>.json fragment file name matches its own asset id', () => {
  for (const file of fragmentFiles) {
    const frag = JSON.parse(readFileSync(new URL(file, FRAGMENT_DIR), 'utf8'))
    assert.equal(file, `${frag.id}.json`, `art/manifest/${file}: id "${frag.id}" does not match the file name`)
  }
})

test('every fragment present in the aggregated ledger matches its fragment exactly (run npm run build:manifest if not)', () => {
  for (const file of fragmentFiles) {
    const frag = JSON.parse(readFileSync(new URL(file, FRAGMENT_DIR), 'utf8'))
    const inAggregate = aggregatedById.get(frag.id)
    if (inAggregate) {
      assert.deepStrictEqual(inAggregate, frag, `art/manifest/${file} has drifted from art/assets-manifest.json — run npm run build:manifest`)
    }
  }
})

test('no asset id appears in the aggregated ledger without a corresponding fragment file', () => {
  for (const asset of aggregated.assets) {
    const expected = `${asset.id}.json`
    assert.ok(fragmentFiles.includes(expected), `art/assets-manifest.json has id "${asset.id}" with no art/manifest/${expected} fragment`)
  }
})
